apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-11-29T12:16:57Z"
  generation: 4
  labels:
    app: redis-master
  name: redis-master
  namespace: default
  resourceVersion: "2014400"
  selfLink: /apis/apps/v1/namespaces/default/deployments/redis-master
  uid: 23698edc-12a2-11ea-8238-42010a8400aa
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-master
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-master
    spec:
      containers:
      - image: gcr.io/robust-zenith-161810/redis-master@sha256:e73ef998c22f9a98793d9951bb2915cd945d8fa6f9ec1b324e85d19617efc2fd
        imagePullPolicy: IfNotPresent
        name: redis-master-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-29T12:16:57Z"
    lastUpdateTime: "2019-11-29T12:17:04Z"
    message: ReplicaSet "redis-master-5784578b57" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-11-29T12:33:44Z"
    lastUpdateTime: "2019-11-29T12:33:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
  
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-29T12:27:50Z"
  labels:
    app: redis-master
  name: redis-master
  namespace: default
  resourceVersion: "2013290"
  selfLink: /api/v1/namespaces/default/services/redis-master
  uid: a848827e-12a3-11ea-8238-42010a8400aa
spec:
  clusterIP: 10.0.20.108
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32322
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-master
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.76.97.37
