apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-service
  namespace: default
  resourceVersion: "2237940"
spec:
  clusterIP: 10.0.31.36
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: default
  resourceVersion: "2237641"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: eu.gcr.io/robust-zenith-161810/tweezen
        imagePullPolicy: Always
        name: tweezen-sha256
      restartPolicy: Always