apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-service
  namespace: default
  resourceVersion: "2055365"
spec:
  clusterIP: 10.0.31.36
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31121
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: default
  resourceVersion: "2055803"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: eu.gcr.io/robust-zenith-161810/tweezen
        imagePullPolicy: Always
        name: tweezen-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30