apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-master
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: gcr.io/robust-zenith-161810/redis-master
        imagePullPolicy: Always
        name: redis-master-sha256