apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-29T15:50:23Z"
  labels:
    app: redis
  name: redis-master
  namespace: default
  resourceVersion: "2055728"
  selfLink: /api/v1/namespaces/default/services/redis-master
  uid: f4049b58-12bf-11ea-8238-42010a8400aa
spec:
  clusterIP: 10.0.23.65
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32629
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-11-29T15:49:56Z"
  generation: 3
  labels:
    app: redis
  name: redis
  namespace: default
  resourceVersion: "2055815"
  selfLink: /apis/apps/v1/namespaces/default/deployments/redis
  uid: e45c9bdd-12bf-11ea-8238-42010a8400aa
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
      - image: gcr.io/robust-zenith-161810/redis-master
        imagePullPolicy: Always
        name: redis-master-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30