apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-29T15:48:59Z"
  labels:
    app: app
  name: app-service
  namespace: default
  resourceVersion: "2055365"
  selfLink: /api/v1/namespaces/default/services/app-service
  uid: c220f747-12bf-11ea-8238-42010a8400aa
spec:
  clusterIP: 10.0.31.36
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31121
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-11-29T15:48:25Z"
  generation: 5
  labels:
    app: app
  name: app
  namespace: default
  resourceVersion: "2055803"
  selfLink: /apis/apps/v1/namespaces/default/deployments/app
  uid: ae3b5aae-12bf-11ea-8238-42010a8400aa
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: eu.gcr.io/robust-zenith-161810/tweezen:1.0
        imagePullPolicy: Always
        name: tweezen-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30